#pragma once

#include <worldanalysis/Export.hpp>
#include <cstddef>
#include <cstdint>
#include <string_view>

namespace worldanalysis::memory {

enum class SignatureId : std::uint16_t {
    VersionString,
    Nametag,
    Fullbright,
    SetupFogPlayer,
    RaknetUpdate,
    NormalTick,
    Time,
    SetTime,
    EduMultiplayer,
    HudCursor,
    LevelInit,
    LevelDtor,
    ActorManagerList,
    DimensionTick,
    WeatherTick,
    WeatherGetRainLevel,
    WeatherGetLightningLevel,
    WeatherIsRaining,
    WeatherIsLightning,
    RenderItem,
    GetFov,
    GetPerspective,
    CameraPlayerVisibilityTick,
    ClientInstanceUpdate,
    ClientInstanceGetLocalPlayer,
    ContainerScreenControllerDtor,
    ContainerScreenControllerOpen,
    ChatScreenDtor,
    ChatScreenOpen,
    BiomeGetTemperature,
    GetDestroyProgress,
    RenderLevel,
    TessellatorBegin,
    TessellatorColor,
    TessellatorVertex,
    MeshHelpersRenderMeshImmediately,
    MeshHelpersRenderMeshImmediately2,
    RenderMaterialGroupCommon,
    SurvivalModeAttack,
    GameModeAttack,
    LevelGetHitResult,
    I18nGetInstance,
    BlockSourceGetBiome,
    BlockSourceGetBlock,
    BlockSourceGetBrightness,
    BlockSourceIsSolidBlockingBlock,
    NavigationComponentGetPath,
    NavigationComponentSetPath,
    PathGetNodeCount,
    PathGetCurrentIndex,
    PathGetPosAtNode,
    PathNavigationAssignPath,
    PathNavigationTickBase,
    PathNavigationTickGeneric,
    PathNavigationTickFlying,
    PathNavigationTickHover,
    PathNavigationTickWallClimber,
    PathNavigationTickWaterBound,
    CameraStateApply,
    LocalPlayerApplyTurnDelta,
    BaseOptionRegistryGetHideItemInHand,
    HitResultGetEntity,
    ActorSetPos,
    ActorSetPosDelta,
    ActorIsPlayer,
    ActorIsInvisible,
    ActorGetHealth,
    ActorGetMaxHealth,
    ActorGetTarget,
    AttributesGetInstanceByName,
    ActorGetEquipmentItem,
    ActorFetchNearbyActorsSorted,
    ActorGetNameTag,
    ActorSetNameTag,
    MinecraftUIRenderContextDrawText,
    ScreenViewRender,
    ContainerScreenControllerOnContainerSlotSelected,
    ContainerScreenControllerGetItemStack,
    ContainerManagerControllerGetItemInstance,
    ClientNetworkHandlerHandleSetTitle,
    ClientNetworkHandlerHandleText,
    LoopbackPacketSenderSendToServer,
    ClientInstanceGetPacketSender,
    MinecraftPacketsCreatePacket,
    LocalPlayerChangeDimension,
    NbtTreeFind,
    ItemStackBaseLoadItem,
    ItemStackBaseGetDamageValue,
    ItemStackBaseGetItem,
    ItemStackBaseGetId,
    ItemActorClientInitialize,
    ItemActorPostNormalTick,
    ItemActorTryGetFromEntity,
    BaseActorRenderContextCtor,
    ItemRendererRenderGuiItemNew,
    MinecraftUIRenderContextRenderItem,
    ControlOptionEditorTick,
    ControlOptionEditorRender,
    BlockTessellatorTessellateFaceDown,
    BlockTessellatorTessellateFaceUp,
    BlockTessellatorTessellateFaceNorth,
    BlockTessellatorTessellateFaceSouth,
    BlockTessellatorTessellateFaceWest,
    BlockTessellatorTessellateFaceEast,
    BlockTessellatorTessellatePane,
    BlockSourceGetBlockForTessellation,
    TextureUVCoordinateSetCopyCtor,
    TextureUVCoordinateSetDtor,
    RenderChunkCoordinatorSetAllDirty,
    DataDrivenModelRender,
    Count
};

inline constexpr std::size_t SignatureCount = static_cast<std::size_t>(SignatureId::Count);

struct SignatureDefinition {
    SignatureId id;
    std::string_view pattern;
};

WORLDANALYSIS_API bool resolveAll(std::string_view libraryName = "libminecraftpe.so");
WORLDANALYSIS_API std::uintptr_t resolve(SignatureId id);
WORLDANALYSIS_API void clear();

}
